force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <label>Picture</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/Movie/MovieController.cls
public with sharing class MovieController {
  @AuraEnabled
  public static void createMovie(
    Movie__c movie,
    List<String> actorsIds,
    String contentDocumentId
  ) {
    String userId = UserInfo.getUserId();

    if (movie != null) {
      insert movie;
      List<MovieActor__c> moviesActors = new List<MovieActor__c>();
      for (String actorId : actorsIds) {
        MovieActor__c movieActor = new MovieActor__c(
          Actor__c = actorId,
          Movie__c = movie.Id
        );
        moviesActors.add(movieActor);
      }
      if (!moviesActors.isEmpty()) {
        insert moviesActors;
      }
      
      FileManagementService.changeContentDocumentLinkedEntity(
        contentDocumentId,
        userId,
        movie.Id
      );
      // ContentVersion contentVersion = [
      //   SELECT Id
      //   FROM ContentVersion
      //   WHERE ContentDocumentId = :contentDocumentId
      // ];

      // movie.Picture__c = contentVersion.Id;
    }
  }

  @AuraEnabled( cacheable = true )
  public static List<Movie__c> getMovies(String movieSearchName){
    String searchCriterie = '%'+movieSearchName+'%';
    List<Movie__c> movies = [SELECT NAME, TYPE__C, RATING__C, PICTURE__C FROM Movie__c WHERE NAME LIKE :searchCriterie];
    System.debug(movies);
    return movies;
  }
}